# Generated by Django 6.0.3 on 2026-03-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('business_travel', models.CharField(max_length=30)),
                ('education_field', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=20)),
                ('overtime', models.CharField(max_length=10)),
                ('monthly_income', models.PositiveIntegerField()),
                ('job_satisfaction', models.PositiveSmallIntegerField()),
                ('environment_satisfaction', models.PositiveSmallIntegerField()),
                ('work_life_balance', models.PositiveSmallIntegerField()),
                ('years_at_company', models.PositiveSmallIntegerField()),
                ('years_in_current_role', models.PositiveSmallIntegerField()),
                ('years_since_last_promotion', models.PositiveSmallIntegerField()),
                ('num_companies_worked', models.PositiveSmallIntegerField()),
                ('distance_from_home', models.PositiveSmallIntegerField()),
                ('percent_salary_hike', models.PositiveSmallIntegerField()),
                ('training_times_last_year', models.PositiveSmallIntegerField()),
                ('job_level', models.PositiveSmallIntegerField()),
                ('prediction', models.PositiveSmallIntegerField()),
                ('attrition_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
